name: 'My composite action'
description: 'Testing composite action'

inputs:
  name:  # id of input
    description: 'a name'
    required: false
    default: 'World'

runs:
  using: "composite"

  steps:
    - run: echo "Hello $NAME"
      shell: bash
      env:
        NAME: ${{ inputs.name }}
